name: Release / Create pull request
description: Commits all modified files to a new release branch and creates a pull request towards the default branch.
author: Steffen Diswal

inputs:
  gh-auth-token:
    description: An authentication token for the GitHub CLI with scopes for `repo` and `read:org` in order to create a pull request.
    required: true
  release-version:
    description: The semantic version number of the new release on the form `major.minor.patch[-prerelease][+buildinfo]` without any `v` prefix.
    required: true

runs:
  using: composite
  steps:
    - name: Validate input parameters # See https://github.com/actions/runner/issues/1070.
      run: |
        if [[ -z "$GH_AUTH_TOKEN" ]]; then
          echo "Input parameter 'gh-auth-token' must be non-empty."
          exit 2
        fi
        if [[ -z "$RELEASE_VERSION" ]]; then
          echo "Input parameter 'release-version' must be non-empty."
          exit 2
        fi
      env:
        GH_AUTH_TOKEN: ${{ inputs.gh-auth-token }}
        RELEASE_VERSION: ${{ inputs.release-version }}
      shell: bash
    - name: Create a release branch
      run: git checkout -b "release/$RELEASE_VERSION"
      env:
        RELEASE_VERSION: ${{ inputs.release-version }}
      shell: bash
    - name: Stage and commit modified files
      run: |
        git add .
        git commit --message "Prepare the release of $RELEASE_VERSION"
        git push --set-upstream origin "release/$RELEASE_VERSION"
      env:
        RELEASE_VERSION: ${{ inputs.release-version }}
      shell: bash
    - name: Fetch the main branch
      run: git fetch origin main # See https://github.com/cli/cli/issues/5896.
      shell: bash
    - name: Create a pull request from the release branch
      run: |
        gh auth login --with-token <<< "$GH_AUTH_TOKEN"
        gh pr create --base main --title "Release $RELEASE_VERSION" --body "This pull request was created automatically by GitHub Actions."
      env:
        GH_AUTH_TOKEN: ${{ inputs.gh-auth-token }}
        RELEASE_VERSION: ${{ inputs.release-version }}
      shell: bash
